Repository SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile, pull requests merged in 2023-10, with the labels that each got.

#24 [network_refinement] Refactor network calls with headers
  mobile/lib/network/network_manager.dart
  mobile/lib/routes/login/bloc/login_event.dart
  mobile/lib/routes/login/model/login_response_model.dart
  mobile/lib/util/router.dart
Labels: enhancement, network, p:mid

#25 [Linter] Add lint rules and make fixes related to linting #5
  mobile/analysis_options.yaml
  mobile/lib/app.dart
  mobile/lib/network/network_manager.dart
  mobile/lib/routes/login/bloc/login_event.dart
  mobile/lib/routes/login/bloc/login_state.dart
  mobile/lib/routes/login/login_route.dart
  mobile/lib/ui/primary_button.dart
  mobile/lib/ui/shows_dialog.dart
  mobile/lib/util/router.dart
  mobile/lib/util/utils.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: enhancement, p:mid

#26 [LoginBlocTest] Add login bloc tests #6
  mobile/pubspec.lock
  mobile/pubspec.yaml
  mobile/test/login_bloc_test.dart
  mobile/test/widget_test.dart
Labels: test

#27 [LoginGoldenTest] Add login golden test #7
  .github/workflows/build_and_upload_apk.yml
  mobile/golden_test/goldens/login/login_route_alert_dialog.png
  mobile/golden_test/goldens/login/login_route_initial.png
  mobile/golden_test/goldens/login/login_route_validation_messages.png
  mobile/golden_test/login_golden_test.dart
  mobile/lib/util/utils.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: test

#29 [BottomBar] Add bottom navigation bar and landing logic #28
  mobile/assets/landing/file-add.png
  mobile/assets/landing/home.png
  mobile/assets/landing/menu.png
  mobile/assets/landing/search.png
  mobile/assets/landing/user.png
  mobile/lib/routes/home/bloc/home_bloc.dart
  mobile/lib/routes/home/bloc/home_event.dart
  mobile/lib/routes/home/bloc/home_state.dart
  mobile/lib/routes/home/home_route.dart
  mobile/lib/routes/landing/bloc/landing_bloc.dart
  mobile/lib/routes/landing/bloc/landing_event.dart
  mobile/lib/routes/landing/bloc/landing_state.dart
  mobile/lib/routes/landing/landing_page.dart
  mobile/lib/routes/login/login_route.dart
  mobile/lib/util/router.dart
  mobile/pubspec.yaml
Labels: design, feature, business logic, p:mid

#31 Feature/30 CI/CD for `dev`
  .github/workflows/build_and_upload_apk.yml
Labels: enhancement, ci/cd

#34 [NavBar] Make bottom nav bar persistent across pages #33
  mobile/lib/routes/landing/bloc/landing_bloc.dart
  mobile/lib/routes/landing/bloc/landing_event.dart
  mobile/lib/routes/landing/bloc/landing_state.dart
  mobile/lib/routes/landing/landing_page.dart
  mobile/lib/util/router.dart
Labels: enhancement, business logic

#36 Feature/23 register
  mobile/ios/Flutter/Debug.xcconfig
  mobile/ios/Flutter/Release.xcconfig
  mobile/lib/routes/register/bloc/register_bloc.dart
  mobile/lib/routes/register/bloc/register_event.dart
  mobile/lib/routes/register/bloc/register_state.dart
  mobile/lib/routes/register/model/register_repository.dart
  mobile/lib/routes/register/model/register_request_model.dart
  mobile/lib/routes/register/model/register_request_model.g.dart
  mobile/lib/routes/register/model/register_response_model.dart
  mobile/lib/routes/register/model/register_response_model.g.dart
  mobile/lib/routes/register/register_route.dart
  mobile/lib/ui/shows_dialog.dart
  mobile/lib/util/api_endpoints.dart
  mobile/lib/util/router.dart
  mobile/lib/util/utils.dart
Labels: feature, business logic

#40 [Register] Improve register appbar design #39
  mobile/assets/register/chevron-left.png
  mobile/lib/routes/home/home_route.dart
  mobile/lib/routes/login/login_route.dart
  mobile/lib/routes/register/register_route.dart
Labels: enhancement, design

#42 [Network] Allow insecure calls for http requests #41
  mobile/android/app/src/main/AndroidManifest.xml
  mobile/ios/Runner/Info.plist
Labels: network
