Repository SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile, pull requests merged in 2023-12, with the labels that each got.

#77 Feature/68 add Makefile for mobile repo
  .github/workflows/build_and_upload_apk.yml
  .github/workflows/test_apk.yml
  Makefile
  hack/flutter-test.ps1
  hack/flutter-test.sh
Labels: ci/cd

#80 Dev->Main #73
  mobile/lib/routes/story_detail/widget/story_tag_chips.dart
Labels: release

#82 Dev->Main
  mobile/lib/routes/create_story/create_story_route.dart
Labels: release

#86 Feature/85 Redefine CI/CD Pipelines
  .github/workflows/build_and_upload_apk.yml
  .github/workflows/test_apk.yml
Labels: ci/cd

#87 Feature/83 remove password validation
  mobile/lib/routes/login/bloc/login_bloc.dart
  mobile/lib/routes/register/bloc/register_bloc.dart
  mobile/test/login_bloc_test.dart
Labels: enhancement

#90 Dev->Main #85 #83 #88
  .github/workflows/build_and_upload_apk.yml
  .github/workflows/test_apk.yml
  mobile/lib/network/network_manager.dart
  mobile/lib/routes/login/bloc/login_bloc.dart
  mobile/lib/routes/register/bloc/register_bloc.dart
  mobile/test/login_bloc_test.dart
Labels: release

#101 [Profile] Avatar operations #92
  mobile/lib/network/network_manager.dart
  mobile/lib/routes/app/model/response/base_response_model.dart
  mobile/lib/routes/login/model/user_details_response_model.dart
  mobile/lib/routes/profile/model/profile_repository.dart
  mobile/lib/routes/profile/model/response/change_avatar_response_model.dart
  mobile/lib/routes/profile/profile_route.dart
  mobile/lib/routes/profile/widget/cached_avatar.dart
  mobile/lib/routes/profile/widget/expanded_header.dart
  mobile/lib/routes/profile/widget/profile_avatar.dart
Labels: design, feature, business logic

#102 Feature/97 Recommendations page
  mobile/lib/routes/home/model/story_model.dart
  mobile/lib/routes/home/model/story_model.g.dart
  mobile/lib/routes/landing/landing_page.dart
  mobile/lib/routes/recommendations/bloc/recommendations_bloc.dart
  mobile/lib/routes/recommendations/bloc/recommendations_event.dart
  mobile/lib/routes/recommendations/bloc/recommendations_state.dart
  mobile/lib/routes/recommendations/model/recommendations_repository.dart
  mobile/lib/routes/recommendations/model/recommendations_response.dart
  mobile/lib/routes/recommendations/model/recommendations_response.g.dart
  mobile/lib/routes/recommendations/recommendations_route.dart
  mobile/lib/util/api_endpoints.dart
Labels: design, feature, business logic, p:mid

#106 Hotfix/105 remove validation of username
  mobile/lib/routes/login/bloc/login_bloc.dart
  mobile/lib/routes/register/bloc/register_bloc.dart
  mobile/test/login_bloc_test.dart
Labels: business logic

#104 Feature/95 story search
  mobile/lib/routes/edit_story/bloc/edit_story_bloc.dart
  mobile/lib/routes/home/bloc/home_bloc.dart
  mobile/lib/routes/landing/landing_page.dart
  mobile/lib/routes/recommendations/bloc/recommendations_bloc.dart
  mobile/lib/routes/search/bloc/search_story_bloc.dart
  mobile/lib/routes/search/bloc/search_story_event.dart
  mobile/lib/routes/search/bloc/search_story_state.dart
  mobile/lib/routes/search/model/search_story_repository.dart
  mobile/lib/routes/search/model/search_story_request_model.dart
  mobile/lib/routes/search/model/search_story_request_model.g.dart
  mobile/lib/routes/search/model/search_story_response_model.dart
  mobile/lib/routes/search/model/search_story_response_model.g.dart
  mobile/lib/routes/search/search_results_route.dart
  mobile/lib/routes/search/search_story_route.dart
  mobile/lib/ui/shows_dialog.dart
  mobile/lib/util/api_endpoints.dart
  mobile/lib/util/router.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: feature, business logic

#103 Feature/84 profile page
  mobile/lib/routes/app/application_context.dart
  mobile/lib/routes/home/bloc/home_bloc.dart
  mobile/lib/routes/login/model/login_repository.dart
  mobile/lib/routes/profile/model/profile_repository.dart
  mobile/lib/routes/profile/profile_route.dart
  mobile/lib/routes/profile/widget/biography_container.dart
  mobile/lib/routes/profile/widget/collapsed_header.dart
  mobile/lib/routes/profile/widget/edit_avatar_button.dart
  mobile/lib/routes/profile/widget/expanded_header.dart
  mobile/lib/routes/profile/widget/profile_avatar.dart
  mobile/lib/routes/profile/widget/story_card.dart
  mobile/lib/routes/story_detail/story_detail_route.dart
  mobile/lib/routes/story_detail/widget/comments_container.dart
  mobile/lib/routes/story_detail/widget/likes_container.dart
  mobile/lib/routes/story_detail/widget/link_button.dart
  mobile/lib/util/api_endpoints.dart
  mobile/lib/util/router.dart
Labels: feature

#111 [Profile] Fix Profile page appbar bug #109
  mobile/lib/routes/profile/profile_route.dart
  mobile/lib/routes/story_detail/widget/story_detail_app_bar.dart
  mobile/lib/util/router.dart
Labels: bug, design

#118 [Profile] Add "Follow" button to user profile page #117
  mobile/lib/routes/profile/model/profile_repository.dart
  mobile/lib/routes/profile/widget/expanded_header.dart
  mobile/lib/routes/profile/widget/follow_button.dart
  mobile/lib/util/api_endpoints.dart
Labels: feature

#116 Feature/115 test coverage
  .github/workflows/build_and_upload_apk.yml
  .github/workflows/test_apk.yml
  hack/flutter-test.ps1
  hack/flutter-test.sh
  hack/lcov-coverage.sh
Labels: test, ci/cd

#123 [Feature] Show error message if profile picture upload fails #122
  mobile/lib/routes/profile/model/profile_repository.dart
  mobile/lib/routes/profile/model/response/add_profile_photo_response_model.dart
  mobile/lib/routes/profile/profile_route.dart
  mobile/lib/routes/profile/widget/edit_avatar_button.dart
  mobile/lib/routes/profile/widget/expanded_header.dart
  mobile/lib/routes/profile/widget/profile_avatar.dart
  mobile/lib/ui/error_alert_dialog.dart
Labels: enhancement

#124 Feature/112 create story tests
  .github/workflows/build_and_upload_apk.yml
  hack/flutter-test.ps1
  hack/flutter-test.sh
  mobile/golden_test/create_story_golden_test.dart
  mobile/lib/routes/create_story/bloc/create_story_bloc.dart
  mobile/lib/util/utils.dart
  mobile/test/create_story_bloc_test.dart
Labels: test

#128 Feature/127 search story tests
  mobile/golden_test/goldens/search_results/search_results_route_initial.png
  mobile/golden_test/goldens/search_results/search_results_route_list.png
  mobile/golden_test/goldens/search_story/search_story_route_initial.png
  mobile/golden_test/search_results_golden_test.dart
  mobile/golden_test/search_story_golden_test.dart
  mobile/lib/routes/search/bloc/search_story_bloc.dart
  mobile/lib/routes/search/search_results_route.dart
  mobile/lib/util/utils.dart
  mobile/test/search_story_bloc_test.dart
Labels: test

#130 110-activity-stream-design-improvements
  mobile/lib/routes/activity_stream/activity_stream_route.dart
Labels: enhancement, design, feature, p:mid

#133 Add commented activity on activity stream
  mobile/lib/routes/activity_stream/activity_stream_route.dart
Labels: enhancement, p:mid

#142 Test/137 increase recommendation test coverage
  mobile/test/recommendations_bloc_test.dart
Labels: test
